### ISSUE TITLE
Nested non empty list generation fail

### ISSUE THREAD

**Issue by zallesov** [typelevel/scalacheck#581] opened 2019-11-04 15:18 UTC
Some changes in 1.14.1 and 1.14.2 make the following test to fail during value generation. With the version 1.14.0, it passes.

This makes it impossible to use generators with nested collections. 

```scala
package io.moia.dispatching
package execution.impl

import org.scalacheck.Gen
class PlaygroundTest extends UnitTest {

//import org.scalactic.anyvals.PosZDouble
//  implicit override val generatorDrivenConfig =
//    PropertyCheckConfiguration(maxDiscardedFactor = PosZDouble(20.0))

  "Playground test" should {

    case class Item(list: List[Int])
    case class Wrapper(list: List[Item])
    case class NestedList(list: List[List[Int]])

    val itemGen: Gen[Item] = for {
      list <- Gen.nonEmptyListOf(Gen.posNum[Int])
    } yield Item(list)

    val wrapperGen: Gen[Wrapper] = for {
      list <- Gen.nonEmptyListOf(itemGen)
    } yield {
      Wrapper(list)
    }

    val nestedGen: Gen[NestedList] = for {
      list <- Gen.nonEmptyListOf(Gen.nonEmptyListOf(Gen.posNum[Int]))
    } yield {
      NestedList(list)
    }

    "Wrapper" in {
      forAll(wrapperGen) { wrapper =>
        wrapper.list.size should (be > 0)
      }
    }

    "Nested" in {
      forAll(nestedGen) { nested =>
        nested.list.size should (be > 0)
      }
    }
  }
}
```
Output
```
[info]  PlaygroundTest:
[info] Playground test
[info] - should Wrapper *** FAILED ***
[info]   Gave up after 6 successful property evaluations. 126 evaluations were discarded.
[info] - should Nested *** FAILED ***
[info]   Gave up after 6 successful property evaluations. 167 evaluations were discarded.
```

I believe the change that results in the issue was introduced here. 
https://github.com/typelevel/scalacheck/blob/1.14.x/src/main/scala/org/scalacheck/Gen.scala#L866

Thank you. 

PS. this looks related https://github.com/typelevel/scalacheck/issues/568
PSS. seems like it is already being fixed in master.

**Comment by ashawley** [comment] 2019-11-04 17:19
Yeah, I know that a fix for part of #568 was merged to master.  I'd need to study this further to see if it handles your case or not.

Incidentally, there are snapshots published when commits are pushed to master.  If you're using sbt, you can use them with the the following snippet:

```scala
resolvers +=
  "Sonatype OSS Snapshots" at
  "https://oss.sonatype.org/content/repositories/snapshots"
```

Then this is the sha version that contains the merge of #569:

```scala
libraryDependencies += "org.scalacheck" %% "scalacheck" % "1.14.2-e3883f6-SNAPSHOT" % "test"
```

Feel free to give it a try and let us know.

**Comment by zakpatterson** [comment] 2019-11-05 16:18
As noted this looks like a duplicate of #568 to me. In 1.14.2, Gen.posNum[Int] will fail to return a value sometimes, basically due to filtering out zeros. nonEmptyListOf, listOfN, etc all fail if the passed generator fails just once.

This does seem to work though given the sha version by @ashawley:

```
> Gen.nonEmptyListOf(Gen.nonEmptyListOf(Gen.nonEmptyListOf(Gen.posNum[Int]))).sample 
res1: Option[List[List[List[Int]]]] = Some(List(List(List(64, 9, 27, 72, 38, 39, 94, 49, 50, 50, 49, 53, 94, 75, 25, 28, 11, 30, 91, 13, 7, 12, 64, 4, 63, 24, 49, 51, 85, 5, 11, 96, 58, 55, 14, 95, 28, 89, 50, 72, 94, 56, 73, 51, 43, 59, 57, 46, 65, 98, 21, 1, 57, 60, 51, 63, 37, 36, 51, 52, 85, 32, 77, 41, 15, 55, 60, 8, 28, 71, 98, 57, 91, 95, 75...
```

**Comment by mdedetrich** [comment] 2019-11-22 12:57
I can also confirm we hit this issue, using the snapshot fixes the regression

**Comment by mikla** [comment] 2019-11-26 22:06
I git the same issue. 
Confirm that `1.14.2-e3883f6-SNAPSHOT` version fixes that.

Thanks everybody!

**Comment by mdedetrich** [comment] 2019-12-03 11:10
Is it possible to make a new release with this fix in there considering this was a pretty serious regression?

**Comment by ashawley** [comment] 2019-12-03 15:37
Yes, it does seem worth releasing, and verifying that the fix doesn't have any regressions.  I'm going to try and cherry-pick the change to the 1.14 branch.  It will probably be a little while until 1.15 is ready.

**Comment by mdedetrich** [comment] 2019-12-03 15:41
>  I'm going to try and cherry-pick the change to the 1.14 branch. It will probably be a little while until 1.15 is ready.

Does this mean there will be a 1.14b release (or something like this?)

**Comment by ashawley** [comment] 2019-12-03 15:43
Current version is 1.14.2.  It will be 1.14.3.

**Comment by mdedetrich** [comment] 2019-12-03 15:49
Ah right, awesome thanks!

**Comment by mdedetrich** [comment] 2019-12-06 10:25
@ashawley Sorry to bug you but  is there an ETA for this? Unfortunately we are hitting https://github.com/coursier/coursier/issues/1149 which means the scalacheck snapshot isn't entirely working for us.

I can also try and set up a PR if that would speed up the process.

**Comment by djspiewak** [comment] 2019-12-12 16:02
I’m happy to do the work of making the release if someone can point me to the appropriate branch/commit. I have the appropriate access to do so.

**Comment by mdedetrich** [comment] 2019-12-12 16:17
@djspiewak This is the PR/commit https://github.com/typelevel/scalacheck/pull/569 . @ashawley said earlier that the safest option would be to cherry pick the above commit in the 1.14.x branch and release 1.14.3 (see https://github.com/typelevel/scalacheck/issues/581#issuecomment-561222879)

**Comment by ashawley** [comment] 2019-12-12 16:46
Sorry for the delay.   I'm just getting back from a trip, and trying to catch up on things.

Thanks for offering to help with publishing, Daniel.  I will likely use it.

I'm going to work on #587 and when that's done I'll work on preparing the 1.14.3 release as Matthew described.

**Comment by djspiewak** [comment] 2019-12-12 17:25
Alrighty, I'll see about helping out a bit later today

**Comment by ashawley** [comment] 2019-12-12 20:02
We can continue the discussion of 1.14.3 in #591

**Comment by SethTisue** [comment] 2019-12-13 07:26
closing because it's a duplicate of #568 (and they are both fixed, though the fix isn't released yet)

**Closed by SethTisue** 2019-12-13 07:26 UTC
