### ISSUE TITLE
Generator produces empty strings when used with forAll

### ISSUE THREAD

**Issue by disordered** [typelevel/scalacheck#650] opened 2020-04-16 14:38 UTC
Tested using `scalacheck-1.14.3` and `scalatestplus-scalacheck-3.1.0.0-RC2`

Is there something I'm doing wrong?
Simplest code that shows the problem:
```
import org.scalacheck.Gen
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatestplus.scalacheck.ScalaCheckPropertyChecks

class TestSpec extends AnyFlatSpec with ScalaCheckPropertyChecks {

  val stringGen = Gen.alphaNumStr.suchThat(_.nonEmpty).retryUntil(_ => true)

  // retryUntil reaches 10001 attempts
  "Test" should "generate values with forAll" in {
    forAll(stringGen) { string =>
      assert(string.nonEmpty)
    }
  }

  // Passes
  it should "generate values with sample" in {
    1.to(1000).foreach { _ =>
      assert(stringGen.sample.get.nonEmpty)
    }
  }
}
```

**Comment by non** [comment] 2020-05-07 02:32
There are a lot of subtle things going on here. Arguably some of these are ScalaCheck bugs and others are problems on the caller side.

First let me describe what the problem is here. ScalaCheck has a max-size parameter that it uses to determine how big to make certain collections, including strings. If this parameter is set too small (for example, to zero) then ScalaCheck will only generate empty strings.

When ScalaCheck runs it usually starts testing with a low size parameter (i.e. zero) and then increases it as tests pass (or are skipped). If you just use `suchThat` to filter out zeros you'll skip this case and move along to places where max-size is larger and ScalaCheck has a chance to generate non-empty strings.

When you use `retryUntil(p)` you're telling ScalaCheck not to skip the value, but try to generate a valid value over and over again using the existing parameters (including max-size) until we are able to generate a value and have that value satisfy `p`. In your case the problem is not satisfying the function `_ => true` but rather in getting a value at all in the first place.

If you removed `retryUntil` then ScalaCheck would filter out the early cases when max-size was zero but then work as expected. Because of the retrying, ScalaCheck keeps trying over and over again to generate a non-empty string (impossible when max-size is zero) and then fails.

(As an aside, it doesn't make sense to use `suchThat(p).retryUntil(_ => true)`. It would be just as good to say `retryUntil(p)` and leave the `suchThat` out of it. This would not fix your issue, but I just thought I should mention it.)

You could argue that ScalaCheck should never test with max-size as zero. However, it's good to start with generating smaller values and working up to larger ones, so I'm not convinced this is a problem. Similarly, you could argue that `retryUntil` should discard the current case, but at that point it's equivalent to using `suchThat`. I think probably the biggest bug here is providing `retryUntil` without explaining how it is different from `suchThat` and without making it clear the ways in which using each of these methods can cause issues like this.

In general, filtering generators is fraught and often leads to various issues (such as failing a test due to too many discards, or getting incredibly slow when used with certain functional patterns such as sequence). I'm sorry you ran into this issue, but I think the best thing you for you to do is to adopt a different strategy instead of such that. Here are some different ways to accomplish this:

```scala
val g0 = Gen.zip(Gen.alphaNumChar, Gen.alphaNumStr).map { case (c, s) => c +: s }
val g1 = Gen.alphaNumStr.map { s => if (s.isEmpty) "abc" else s }
val g2 = Gen.nonEmptyListOf(Gen.aphaNumChar).map(_.mkString)
```

**Comment by non** [comment] 2020-05-07 12:45
I overlooked one more way you could fix this:

```scala
val gen = Gen.resize(10, Gen.alphaNumStr.suchThat(_.nonEmpty).retryUntil(_ => true))
```

The `Gen.resize` method fixes the size parameter, ignoring the value ScalaCheck threads through. This avoids the issue where the value starts at zero and the generator gets stuck trying to retry.

I'd like to close this issue since it doesn't describe a specific bug -- if there are specific things we want to change about ScalaCheck we can open new issues. How does that sound?

**Comment by disordered** [comment] 2020-05-07 13:27
@non , thanks for detailed explanation and examples. I think the `g1` solution is best as it is clear what the intent is.
I tried figuring out why it wasn't working but didn't really get anywhere, so my suggestion would be to hint in `retryUntil` documentation that it can get stuck in retry loop. On the other hand maybe it is my own misinterpretation since docs state:
```
Create a generator that calls this generator repeatedly until the given condition is fulfilled.
```

Alternatively, maybe you could consider introducing an alternative "retry" (can't think of a good name right now) that works like `suchThat` but will generate next value instead of exiting with nothing? In essence, I started with `suchThat` and attached a `retryUntil` to get next value in case `suchThat` discards it. Something like `Gen.alphaNumStr.suchThat(_.nonEmpty).nextOnFail`
I guess I should create a separate issue for this suggestion?

**Comment by non** [comment] 2020-05-07 15:11
@disordered Did you just try `suchThat`? What problems did you encounter with that?

**Comment by disordered** [comment] 2020-05-07 16:19
Well, it is not a problem, but `suchThat` returns `None` if predicate fails. If I had to deal with `None`, I would simply map it to non-empty value either by resampling or just `map`, so I was expecting `retryUntil` to just generate next value for me. I think `suchThat` is working as documented.

**Comment by non** [comment] 2020-05-07 16:52
@disordered Thanks for the clarification (I was in the midst of writing a reply noting that `suchThat` doesn't change the type of `Gen[T]`). This makes sense.

Anyway, it's unfortunate that your example happens to hit a bunch of strange edges of ScalaCheck, but I'm glad we have some work-arounds which should do well for you.

OK to close this now?

**Comment by disordered** [comment] 2020-05-07 16:55
Ye I think we can close this. Should I create a separate issue for the "nextOnFail"? I'm not sure if it makes sense to add such feature or just our scenario.

**Comment by non** [comment] 2020-05-07 17:13
@disordered I think it's OK to open an issue but unless we get several other people clamoring for it we probably won't add it (since it really only makes sense when using `sample`, and you can handle this at the `sample` call instead):

```scala
implicit class Resample[A](g: Gen[A]) {
  def resample(retries: Int = 1000): A = {
    def loop(tries: Int): A =
      if (tries >= retries) sys.error("!")
      else g.sample match {
        case Some(a) => a
        case None => loop(tries + 1)
      }
    loop(0)
  }
}
```

**Closed** 2020-05-07 17:13 UTC
