### ISSUE TITLE
Gen.choose in 1.13.4 (or 1.13.x?) ignores its range

### ISSUE THREAD

**Issue by Kevin-Lee** [typelevel/scalacheck#347] opened 2017-07-23 17:45 UTC
`org.scalacheck.Gen.choose` in 1.13.4 (or maybe 1.13.x) seems to ignore its range when it gets a failed test.
For instance, when the following check fails, I think the `ARG_0` should be 10 but it isn't. 
```scala
property("a number should be between 1 and 10") =
  forAll(Gen.choose(1, 10)) { x =>
    println(s"x: $x")
    x > 0 && x < 10 // deliberately made it < 10 so that it fails when x is 10
  }
```
In my case, it gives me 0 which shouldn't be given by `Gen.choose(1, 10)`.

* Result:
```
x: 8
x: 7
x: 10
x: 5
x: -5
x: -2
x: -1
x: 0
! GenChooseSpec.: Falsified after 2 passed tests.
> ARG_0: 0
> ARG_0_ORIGINAL: 10
Found 1 failing properties.
```
As you can see, it even supplies a negative number.
I can see that an old version like 1.12.6 doesn't have this issue.

**Comment by Kevin-Lee** [comment] 2017-08-01 12:44
Because of this issue, all other gen methods using `choose` (e.g. `numChar`, `alphaUpperChar`, `alphaLowerChar`, `alphaChar`, `alphaNumChar`, `numStr`, `alphaUpperStr`, `alphaLowerStr`, `alphaStr`, `alphaNumStr`, and so on) are broken as well.
e.g.)
`Gen.alphaStr` sometimes gives me `Int` values or some symbols like `+`.

I can't use 1.12.x versions because there is another issue in there (more precisely when using it with Scalatest).

I'm just wondering how this could happen. The test framework was released without testing itself? 😞

**Comment by Kevin-Lee** [comment] 2017-08-01 12:54
I just saw #317. If it's an already known issue, how come I don't have this in 1.12.x? Does that mean I was just lucky when I was using 1.12.x? 🤔

**Comment by rickynils** [comment] 2017-08-02 16:14
@Kevin-Lee I guess you were lucky, but there might have been changes that affected the behavior.

Also, please note that you will only get those unexpected values when ScalaCheck actually have found errors in your code with "correct" values. Shrinking is only performed after an error has been found, so if you find and fix the errors in your code (or property), you will not get unexpected values.

**Comment by ashawley** [comment] 2021-04-08 04:02
Closing as a duplicate of the long-standing issue #129 where shrinking disregards any filters on an explicit Gen.

**Closed by ashawley** 2021-04-08 04:02 UTC
