### ISSUE TITLE
Gen.chooseNum(0, Int.MaxValue) sometimes gives -1073741823

### ISSUE THREAD

**Issue by shawjef3** [typelevel/scalacheck#338] opened 2017-06-16 16:11 UTC
I would expect this to not give any negative values.

**Comment by shawjef3** [comment] 2017-06-16 16:11
As a work around, I'm using `Gen.choose(0, Int.MaxValue)`.

**Comment by shawjef3** [comment] 2017-06-16 16:15
Actually, `Gen.choose` isn't a good workaround, because it doesn't test extrema.

**Comment by shawjef3** [comment] 2017-06-16 16:16
I'm using scalacheck 1.13.5 for scala 2.11.

**Comment by Philippus** [comment] 2018-07-22 11:18
could you share an example? So far, I cannot reproduce this.

**Comment by ashawley** [comment] 2018-07-23 13:52
Agree.  I cant 'get the most naive test of this to fail:

```scala
    Prop.forAll(Gen.choose(0, Int.MaxValue)) { x: Int =>
      0 <= x && x <= Int.MaxValue
    }
```

When I intentionally modified the test so it fails, I did see that the shrinking could produce a negative.  

```
> ARG_0: -1
> ARG_0_ORIGINAL: 1967653363
```

That's a known issue with shrinkers, see #129, not with the generators.

**Comment by pford19** [comment] 2018-09-12 16:03
Curious about the issue tracking and lifecycle process. Why is this issue still in Open status?

**Comment by rickynils** [comment] 2018-09-13 09:10
@pford19 Lack of time. I want to bring in more maintainers and get better project management for ScalaCheck, but I have unfortunately not time for that either.

**Comment by pford19** [comment] 2018-09-13 13:04
:-)

**Comment by SethTisue** [comment] 2019-09-03 02:43
sounds like maybe we should just close this, since there's no clear issue here that isn't #129?

**Comment by non** [comment] 2019-09-03 04:01
Agreed, I think that issue tracks the problem, and `-disableLegacyShrinking` is a work around for it.

**Closed** 2019-09-03 04:01 UTC

**Comment by plokhotnyuk** [comment] 2019-09-03 04:29
@non am I understand correctly that disabling of legacy shrinking is not turned on by default in latest versions?
